from Producto import *
S = "====================================================="
Producto1 = Producto("Licuadora", "Oster", "Electrodoméstcos", 1600.0 )
Producto1.MostrarDetalles()
print(S)
Producto2 = Producto("Whiskas,delicias rellenas", "Whiskas","Mascotas", 54.50)
Producto2.MostrarDetalles()
print(S)
Producto3 = Producto("Aceite de coco", "San Lucas", "Despensa", 69.0)
Producto3.MostrarDetalles()
print(S)
Producto4 = Producto("Lavadora", "Whirpool", "Electrodomésticos", 3500.0)
Producto4.MostrarDetalles()
print(S)
Producto5 = Producto("Cepillo de dientes", "Colgate", "Higiene bucal", 45.0)
Producto5.MostrarDetalles()
